/*Take an amount from user & pay it using currency available eg.2000,500,200,100,50,20,10,5,2,1.*/
#include<stdio.h>
int main()
{
	int amount,notes;
	printf("\nEnter amount: ");
	scanf("%d",&amount);
	if(amount>=2000)
	{
		notes=amount/2000;
		amount=amount%2000;
		printf("\n2000*%d",notes);
	}
	if(amount>=500)
	{
		notes=amount/500;
		amount=amount%500;
		printf("\n500*%d",notes);
	}
	if(amount>=200)
	{
		notes=amount/200;
		amount=amount%200;
		printf("\n200*%d",notes);
	}
	if(amount>=100)
	{
		notes=amount/100;
		amount=amount%100;
		printf("\n100*%d",notes);
	}
	if(amount>=50)
	{
		notes=amount/50;
		amount=amount%50;
		printf("\n50*%d",notes);
	}
	if(amount>=20)
	{
		notes=amount/20;
		amount=amount%20;
		printf("\n20*%d",notes);
	}
	if(amount>=10)
	{
		notes=amount/10;
		amount=amount%10;
		printf("\n10*%d",notes);
	}
	if(amount>=5)
	{
		notes=amount/5;
		amount=amount%5;
		printf("\n5*%d",notes);
	}
	if(amount>=2)
	{
		notes=amount/2;
		amount=amount%2;
		printf("\n2*%d",notes);
	}
	if(amount>=1)
	{
		notes=amount/1;
		amount=amount%51;
		printf("\n1*%d",notes);
	}	
}
